# Generated by Django 4.2.23 on 2025-09-22 06:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.roles
import nautobot.extras.models.statuses


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0114_computedfield_grouping'),
        ('ipam', '0047_alter_ipaddress_role_alter_ipaddress_status_and_more'),
        ('dcim', '0062_module_data_migration'),
        ('nautobot_ssot_demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuniperInterface',
            fields=[
                ('enabled', models.BooleanField(default=True)),
                ('mac_address', nautobot.core.models.fields.MACAddressCharField(blank=True, default='')),
                ('mtu', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65536)])),
                ('mode', models.CharField(blank=True, max_length=50)),
                ('interface', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dcim.interface')),
                ('vlan_tagging', models.BooleanField(default=False)),
                ('flexible_vlan_tagging', models.BooleanField(default=False)),
                ('bridge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bridged_interfaces', to='nautobot_ssot_demo.juniperinterface')),
                ('parent_interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_interfaces', to='nautobot_ssot_demo.juniperinterface')),
                ('role', nautobot.extras.models.roles.RoleField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='extras.role')),
                ('router_vlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipam.vlan')),
                ('status', nautobot.extras.models.statuses.StatusField(on_delete=django.db.models.deletion.PROTECT, to='extras.status')),
            ],
            options={
                'ordering': ['interface', 'vlan_tagging', 'flexible_vlan_tagging', 'router_vlan'],
            },
        ),
    ]
