# Generated by Django 4.2.23 on 2025-09-22 07:19

import django.core.serializers.json
from django.db import migrations, models
import nautobot.core.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0114_computedfield_grouping'),
        ('nautobot_ssot_demo', '0002_juniperinterface'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juniperinterface',
            options={'ordering': ['vlan_tagging', 'flexible_vlan_tagging', 'router_vlan']},
        ),
        migrations.RemoveField(
            model_name='juniperinterface',
            name='bridge',
        ),
        migrations.RemoveField(
            model_name='juniperinterface',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='juniperinterface',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='juniperinterface',
            name='mac_address',
        ),
        migrations.RemoveField(
            model_name='juniperinterface',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='juniperinterface',
            name='mtu',
        ),
        migrations.RemoveField(
            model_name='juniperinterface',
            name='parent_interface',
        ),
        migrations.RemoveField(
            model_name='juniperinterface',
            name='role',
        ),
        migrations.RemoveField(
            model_name='juniperinterface',
            name='status',
        ),
        migrations.AddField(
            model_name='juniperinterface',
            name='_custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='juniperinterface',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='juniperinterface',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='juniperinterface',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='juniperinterface',
            name='tags',
            field=nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag'),
        ),
    ]
