# Generated by Django 4.2.23 on 2025-09-22 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0062_module_data_migration'),
        ('nautobot_ssot_demo', '0003_alter_juniperinterface_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juniperinterface',
            options={'ordering': ['interface', 'vlan_tagging', 'flexible_vlan_tagging', 'router_vlan']},
        ),
        migrations.AddField(
            model_name='juniperinterface',
            name='interface',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.interface'),
        ),
    ]
